### ISSUE TITLE
Release x.y.z - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#1346]
**Planned RC1: ~2+ weeks before a stable, mayor talk-server release / replace with date**

**Bump (do this when creating new roadmap)**
- [ ] create milestone
- [ ] bump version in MainApp
- [ ] check if oldest Android version is EOL by Google and user usage <= 0.5% and drop it if so
  - [ ] search for usage of Build.VERSION_CODES.xy
  - [ ] announce it in changelog

**Create stable-x.y branch & use it for release (when releasing RC1)**
- [ ] create branch ```stable-x.y```
	- [ ] enable branch to be analyzed on codacy
- [ ] change on App
	- [ ] ```drone.yml``` (```master```-->```stable-x.y```)
	- [ ] ```getBranchName.sh``` (```master```-->```stable-x.y```)
	- [ ] ```analysis-wrapper.sh``` (```master```-->```stable-x.y```)
	- [ ] check that transifex bot still works
- [ ] Update version on ```master``` to next major version

**Test app with all supported Android versions**
- access all activities/controllers
- chat: previews (media/contacts), text/voice-messages, reply/swipe-reply, delete, share file
- call: audio/video
- switch accounts
- dark/light theme

All tests on
  - [ ] Android 5
  - [ ] Android 6
  - [ ] Android 7
  - [ ] Android 8
  - [ ] Android 9
  - [ ] Android 10
  - [ ] Android 11

**RC1**
- [ ] Bump version code in ```build.gradle``` file
- [ ] replace screenshots (https://github.com/nextcloud/screenshots/tree/master/android/phone)
- [ ] Verify that the new version number is shown in settings
- [ ] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] ~~release with fastlane: creates GH release, uploads to Gplay, creates Gitlab MR for F-Droid~~
- [ ] Verify that it is shown on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (within 24h)
- [ ] inform marketing about changelog and expected release date

**Final Release, after two weeks time (max) of latest RC release**
- [ ] Bump version code in ```build.gradle``` file
- [ ] Verify that the new version number is shown in settings
- [ ] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] ~~release with fastlane: creates GH release, uploads to Gplay, creates Gitlab MR for F-Droid~~
- [ ] Verify that it is shown on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (within 24h)

**After release**
- x.y-1
  - [ ] delete ```stable-x.y-1``` branch
- x.y
  - [ ] create milestone x.y.1
  - [ ] schedule x.y.1 RC1 3 weeks after stable, release ~4 weeks
  - [ ] create overview issue
- x.y+1
  - [ ] create milestone x.y+1
  - [ ] create overview issue & adjust date, handle bumps

Backports:
- [App](https://github.com/nextcloud/talk-android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

Open PRs:
- [Milestone](https://github.com/nextcloud/talk-android/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Nextcloud+App+12.0.0%22)

Marketing:
@jospoortvliet

**Comment by nickvergessen** [comment]
On new majors the branch pattern in
https://github.com/nextcloud/docker-ci/blob/master/translations/handlePlainTranslations.sh#L15-L17
also needs to be adjusted
