### ISSUE TITLE
Release x.y.Z - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#1347]
**Planned RC1: ~3 weeks after previous stable release / replace with date**

- [ ] Bump version code in ```build.gradle``` file
- [ ] Verify that the new version number is shown in settings
- [ ] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] ~~release with fastlane: creates GH release, uploads to Gplay, creates Gitlab MR for F-Droid~~
- [ ] Verify that it is shown on [F-Droid](https://f-droid.org/de/packages/com.nextcloud.client/) (within 24h)
- [ ] inform marketing about changelog and expected release date

**Final Release, after one weeks time (max) of latest RC release**
- [ ] Bump version code in ```build.gradle``` file
- [ ] release new library if needed
- [ ] Verify that the new version number is shown in settings
- [ ] Verify that logging is disabled
- [ ] Test that what's new is shown correctly on upgrade
- [ ] add $version.txt to /fastlane/metadata/android/en-US/changelogs/ to support GPlay version info
- [x] ~~release with fastlane: creates GH release, uploads to Gplay, creates Gitlab MR for F-Droid~~
- [ ] Verify that it is shown on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (within 24h)

Backports:
- [App backport requests](https://github.com/talk-android/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
