### ISSUE TITLE
Release 12.1.0 - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#1348]
**Planned RC1: 23.06.2021**

**Bump (do this when creating new roadmap)**
- [x] create milestone
- [x] bump version in MainApp
- [x] check if oldest Android version is EOL by Google and user usage <= 0.5% and drop it if so
  - [x] search for usage of Build.VERSION_CODES.xy
  - [x] announce it in changelog

**Create stable-x.y branch & use it for release (when releasing RC1)**
- [x] create branch ```stable-x.y```
	- [x] enable branch to be analyzed on codacy
- [x] change on App
	- [x] ```drone.yml``` (```master```-->```stable-x.y```)
	- [x] ```getBranchName.sh``` (```master```-->```stable-x.y```)
	- [x] ```analysis-wrapper.sh``` (```master```-->```stable-x.y```)
	- [x] check that transifex bot still works
- [x] Update version on ```master``` to next major (or minor) version

**Test app with all supported Android versions**
- access all activities/controllers
- chat: previews (media/contacts), text/voice-messages, reply/swipe-reply, delete, share file
- call: audio/video
- switch accounts
- dark/light theme

All tests on
  - [x] Android 5
  - [x] Android 6
  - [x] Android 7
  - [x] Android 8
  - [x] Android 9
  - [x] Android 10
  - [x] Android 11

**RC1**
- [x] Bump version code in ```build.gradle``` file to ```120000051```
- [x] replace screenshots (https://github.com/nextcloud/screenshots/)
- [x] Verify that the new version number is shown in settings
- [x] ~~Verify that it is shown on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (within 24h)~~
- [x] inform marketing about changelog and expected release date

**Final Release, after two weeks time (max) of latest RC release**
- [x] Bump version code in ```build.gradle``` file to ```120000090```
- [x] Verify that the new version number is shown in settings
- [x] Tag version as "v```x.y.z```" (as in ```^v[0-9]+\.[0-9]+\.[0-9]+$```)
- [x] Verify that it is shown on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (within 24h)

**After release**
- x.y-1
  - [x] ~~delete ```stable-11``` branch~~
- x.y
  - [x] create milestone 12.1.1
  - [x] schedule 12.1.1 RC1 - 3 weeks after stable, release ~4 weeks
  - [x] create overview issue
- x.y+1
  - [x] create milestone 12.2.0
  - [x] create overview issue & adjust date, handle bumps

Backports:
- [App backport requests](https://github.com/nextcloud/talk-android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

Open PRs:
- [Milestone](https://github.com/nextcloud/talk-android/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Nextcloud+App+12.1.0%22)

Marketing:
@jospoortvliet

**Comment by AndyScherzinger** [comment]
@mahibi @nickvergessen can we delete the ```stable-11``` branch or do we need to keep it for enterprise customers?

**Comment by mahibi** [comment]
i hope we won't need it anymore but let's keep it alive a little longer just in case....

**Comment by AndyScherzinger** [comment]
planned it for 12.2.0 ToDos now 👍

**Comment by nickvergessen** [comment]
I would always keep the stable- branches

**Comment by AndyScherzinger** [comment]
> I would always keep the stable- branches

I would never keep them except the last one, because:
* If we ever need to fix something that far back, we can branch of a tag which is a fixed/defined "state" of the app
* We auto-merge/share translations throughout the ```master```/```stable_```+ branches, so you would keep legacy string forever

I personally don't see a reason to keep dead branches anywhere, not sure how we handle this on the server-side but there are branches and tags for a reason in (D)VCSs. (While I look at things in an academic way every now and then...)

**Comment by nickvergessen** [comment]
I just leave this here:
https://github.com/nextcloud/server/tree/stable9

It's history and records.


> We auto-merge/share translations throughout the master/stable_+ branches, so you would keep legacy string forever


That could be an argument, but we could also adjust the pattern in
https://github.com/nextcloud/docker-ci/blob/94ae6b63f5b1e8c4ae845a2a10ad3adbc02f60f6/translations/handlePlainTranslations.sh#L14
like in 
https://github.com/nextcloud/docker-ci/blob/94ae6b63f5b1e8c4ae845a2a10ad3adbc02f60f6/translations/handleAppTranslations.sh#L16

**Comment by AndyScherzinger** [comment]
> I just leave this here

😆 Cheers!

I am fine either way so feel free to keep the branches, just my personal opinion that tags are for documentation and branches for work.

> That could be an argument, but we could also adjust the pattern

A somewhat general discussion convention or configuration / explicit or implicit...

The only thing important to me would be alignment between files and talk (Android at least) since having to different mechanisms is bad from a knowledge perspective looking a general maintainability / mutual benefits/sharing and ramp-up times for onboarding or lending a hand :(

Looking at files we move thing towards conventions (e.g. today @tobiasKaminsky moved scripts to check ```stable-*```).
So maybe a discussion for later/company week

**Comment by nickvergessen** [comment]
> A somewhat general discussion convention or configuration / explicit or implicit...

Well currently any of the 600 contributors could push a branch `stable-i-break-translations` and revert https://github.com/nextcloud/talk-android/pull/1403 in it. The string would be synced to transifex, translators break translations again...

Speaking of which, branch protection in this repo is `master` and `v[0-9].[0-9].x` atm, I will add `stable-[0-9.]*` to it

**Comment by AndyScherzinger** [comment]
> Speaking of which, branch protection in this repo is `master` and `v[0-9].[0-9].x` atm, I will add `stable-[0-9.]*` to it

perfect 👍

> Well currently any of the 600 contributors could push a branch `stable-i-break-translations` and revert https://github.com/nextcloud/talk-android/pull/1403 in it. The string would be synced to transifex, translators break translations again...

Good point! So making it explicit and a rather configurable thing seems to be better suited then (while it then be nice to have this automated of course 😬)
