### ISSUE TITLE
Release 12.1.1 - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#1407]
**Planned RC1: 03.08.2021**

- [x] ~~Bump ```versionCode``` in ```app/build.gradle``` file~~
- [x] ~~Verify that the new version number is shown in settings~~

- [x] ~~Verify that it is shown on [F-Droid](https://f-droid.org/de/packages/com.nextcloud.client/) (within 24h)~~
- [x] ~~Inform marketing about changelog and expected release date~~

**Final Release, after one weeks time (max) of latest RC release**
- [x] Bump ```versionCode``` in ```app/build.gradle``` file
- [x] Verify that the new version number is shown in settings

- [x] ~~Verify that it is shown on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (within 24h)~~
- [x] In case there were security issues fixed ping the security team

Backports:
- [App backport requests](https://github.com/talk-android/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
