### ISSUE TITLE
Release 12.2.1 - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#1408]
**Planned RC1: 17.08.2021**

**Release/EOL Management preparations (do this when creating new roadmap)**
- [x] [Create milestone](https://github.com/nextcloud/talk-android/milestones/new)
- [x] Check if oldest Android version is EOL by Google and user usage <= 0.5% and drop it if so
  - [x] Search for usage of Build.VERSION_CODES.xy
  - [x] Announce it in [changelog](https://github.com/nextcloud/talk-android/blob/master/CHANGELOG.md)

**Create stable-12.2 branch & use it for release (when releasing RC1)**
- [x] Create branch ```stable-12.2```
	- [x] Enable branch to be analyzed on [codacy](https://app.codacy.com/gh/nextcloud/talk-android/settings/branches)
- [x] Change on App
	- [x] Change ```drone.yml``` (```master```-->```stable-12.2```)
	- [x] Change ```scripts/analysis/getBranchName.sh``` (```master```-->```stable-12.2```)
	- [x] Change ```scripts/analysis/analysis-wrapper.sh``` (```master```-->```stable-12.2```)
	- [x] Check that transifex bot still works
- [x] Update versionCode in ```app/build.gradle``` on ```master``` to next major version

**Test app with all supported Android versions**
- Access all activities/controllers
- Chat: previews (media/contacts), text/voice-messages, reply/swipe-reply, delete, share file
- Call: audio/video
- Switch accounts
- Dark/light theme

All tests on
  - [x] Android 5
  - [x] Android 6
  - [x] Android 7
  - [x] Android 8
  - [x] Android 9
  - [x] Android 10
  - [x] Android 11

**RC1**
- [x] Bump versionCode in ```app/build.gradle``` file
- [x] Replace screenshots (https://github.com/nextcloud/screenshots/)
- [x] Verify that the new version number is shown in settings

- [x] Verify that it is shown on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (within 24h)
- [x] Inform marketing about changelog and expected release date

**Final Release, after two weeks time (max) of latest RC release**
- [x] Bump versionCode in ```app/build.gradle``` file
- [x] Verify that the new version number is shown in settings
- [x] Tag version as "v```x.y.z```" (as in ```^v[0-9]+\.[0-9]+\.[0-9]+$```)

- [x] Verify that it is shown on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (within 24h)
- [x] In case there were security issues fixed ping the security team

**After release**
- ```x.y``` - 1
  - [x] Delete ```stable-11``` branch
  - [x] Delete ```stable-12.1``` branch
- ```x.y```
  - [x] Create milestone ```12.2.1```
  - [x] Schedule ```12.2.1 RC1``` 3 weeks after stable, release _~4 weeks_
  - [x] Create overview issue
- ```x.y``` + 1
  - [x] Create milestone ```12.3.0```
  - [x] Create overview issue & adjust date, handle bumps

Backports:
- [App backport requests](https://github.com/nextcloud/talk-android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

Open PRs:
- [Milestone](https://github.com/nextcloud/talk-android/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Nextcloud+App+12.2.0%22)

Marketing:
@jospoortvliet
