### ISSUE TITLE
Release 12.1.2 - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#1450]
**Planned: 16.07.2021**

- [x] Bump ```versionCode``` in ```app/build.gradle``` file
- [x] Verify that the new version number is shown in settings

- [x] ~~Verify that it is shown on [F-Droid](https://f-droid.org/de/packages/com.nextcloud.client/) (within 24h)~~
- [x] Inform marketing about changelog and expected release date

**Final Release, after one weeks time (max) of latest RC release**
- [x] Bump ```versionCode``` in ```app/build.gradle``` file
- [x] Verify that the new version number is shown in settings

- [x] Verify that it is shown on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (within 24h)
- [x] ~~In case there were security issues fixed ping the security team~~

Backports:
- [App backport requests](https://github.com/talk-android/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

**Comment by AndyScherzinger** [comment]
@Bubu Sorry for pinging you here but could you maybe have a look? https://gitlab.com/fdroid/fdroiddata/-/commits/master/metadata/com.nextcloud.talk2.yml

Meta data has been updated for 12.1.0, 12.1.1 and 12.1.0 in the last days/week but still no publishing of any of the versions happened: https://f-droid.org/de/packages/com.nextcloud.talk2/

**Comment by AndyScherzinger** [comment]
Also pinged Izzy @ https://gitlab.com/fdroid/fdroiddata/-/commit/e4022a54c06463122b4523a09d955651322d26f5#note_629387637

**Comment by Bubu** [comment]
I'm not sure what's going wrong, but you can find the last 2 build logs here: https://bubu1.eu/fdroid/repo/com.nextcloud.talk2_120010090.log.gz and https://bubu1.eu/fdroid/repo/com.nextcloud.talk2_120010190.log.gz (mirror because f-droid.org is stupidly slow.)


 12.1.2 hasn't had yet a build attempt as far as I can see.

**Comment by AndyScherzinger** [comment]
> I'm not sure what's going wrong

I had that a while ago and did a complete fresh checkout, but ```git remote prune origin``` might help too :/ Is there a way to have fresh / clean checkout? Else I'd guess this will keep failing

**Comment by Bubu** [comment]
This should be happening when you change the repoUrl for the fdroid metadata and let the buildserver process that once, then change it back.

(i.e. you could build from a personal fork for the next iteration, or if that doesn't work for some reason then just change it to some random repo and let it fail once or something like that )

**Comment by AndyScherzinger** [comment]
Thanks. Izzy removed the last commit so I guess it'll detect 12.1.2 again tonight and fail again 🙈

**Comment by AndyScherzinger** [comment]
f-droid published 12.1.2 today 🚀
