### ISSUE TITLE
Release 12.3.0 - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#1573]
**Planned RC1: ~2+ weeks before a stable, mayor talk-server release / replace with date**

**Release/EOL Management preparations (do this when creating new roadmap)**
- [ ] [Create milestone](https://github.com/nextcloud/talk-android/milestones/new)
- [ ] Check if oldest Android version is EOL by Google and user usage <= 0.5% and drop it if so
  - [ ] Search for usage of Build.VERSION_CODES.xy
  - [ ] Announce it in [changelog](https://github.com/nextcloud/talk-android/blob/master/CHANGELOG.md)

**Create stable-x.y branch & use it for release (when releasing RC1)**
- [ ] Create branch ```stable-x.y```
	- [ ] Enable branch to be analyzed on [codacy](https://app.codacy.com/gh/nextcloud/talk-android/settings/branches)
- [ ] Change on App
	- [x] Change ```drone.yml``` (```master```-->```stable-x.y```)
	- [x] Change ```scripts/analysis/getBranchName.sh``` (```master```-->```stable-x.y```)
	- [x] Change ```scripts/analysis/analysis-wrapper.sh``` (```master```-->```stable-x.y```)
	- [ ] Check that transifex bot still works
- [ ] Update versionCode in ```app/build.gradle``` on ```master``` to next major version

**Test app with all supported Android versions**
- Access all activities/controllers
- Chat: previews (media/contacts), text/voice-messages, reply/swipe-reply, delete, share file
- Call: audio/video
- Switch accounts
- Dark/light theme

All tests on
  - [ ] Android 5
  - [ ] Android 6
  - [ ] Android 7
  - [ ] Android 8
  - [ ] Android 9
  - [ ] Android 10
  - [ ] Android 11

**RC1**
- [ ] Bump versionCode in ```app/build.gradle``` file
- [ ] Replace screenshots (https://github.com/nextcloud/screenshots/)
- [x] Verify that the new version number is shown in settings

- [ ] Verify that it is shown on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (within 24h)
- [ ] Inform marketing about changelog and expected release date

**Final Release, after two weeks time (max) of latest RC release**
- [ ] Bump versionCode in ```app/build.gradle``` file
- [ ] Verify that the new version number is shown in settings
- [ ] Tag version as "v```x.y.z```" (as in ```^v[0-9]+\.[0-9]+\.[0-9]+$```)

- [ ] Verify that it is shown on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (within 24h)
- [ ] In case there were security issues fixed ping the security team

**After release**
- ```x.y``` - 1
  - [ ] Delete ```stable-x.y-1``` branch
- ```x.y```
  - [ ] Create milestone ```vx.y.1```
  - [ ] Schedule ```x.y.1 RC1``` 3 weeks after stable, release _~4 weeks_
  - [ ] Create overview issue
- ```x.y``` + 1
  - [ ] Create milestone ```x.y```+1
  - [ ] Create overview issue & adjust date, handle bumps

Backports:
- [App backport requests](https://github.com/nextcloud/talk-android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

Open PRs:
- [Milestone](https://github.com/nextcloud/talk-android/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Nextcloud+App+12.3.0%22)

Marketing:
@jospoortvliet
