### ISSUE TITLE
Release 13.0.0 - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#1647]
**Planned RC1: ~2+ weeks before a stable, mayor talk-server release / replace with date**

**Release/EOL Management preparations (do this when creating new roadmap)**
- [x] [Create milestone](https://github.com/nextcloud/talk-android/milestones/new)
- [x] Check if oldest Android version is EOL by Google and user usage <= 0.5% and drop it if so
  - [x] Search for usage of Build.VERSION_CODES.xy
  - [x] Announce it in [changelog](https://github.com/nextcloud/talk-android/blob/master/CHANGELOG.md)

**Create stable-x.y branch & use it for release (when releasing RC1)**
- [x] Create branch ```stable-13.0```
	- [x] Enable branch to be analyzed on [codacy](https://app.codacy.com/gh/nextcloud/talk-android/settings/branches)
- [x] Change on App
	- [x] Change ```drone.yml``` (```master```-->```stable-13.0```)
	- [x] Change ```scripts/analysis/getBranchName.sh``` (```master```-->```stable-13.0```)
	- [x] Change ```scripts/analysis/analysis-wrapper.sh``` (```master```-->```stable-13.0```)
	- [x] Check that transifex bot still works
- [x] Update versionCode in ```app/build.gradle``` on ```master``` to next major version

**Test app with all supported Android versions**
- Access all activities/controllers
- Chat: previews (media/contacts), text/voice-messages, reply/swipe-reply, delete, share file
- Call: audio/video
- Switch accounts
- Dark/light theme

All tests on
  - [x] Android 5
  - [x] Android 6
  - [x] Android 7
  - [x] Android 8
  - [x] Android 9
  - [x] Android 10
  - [x] Android 11

**RC1**
- [x] Bump versionCode in ```app/build.gradle``` file
- [x] Replace screenshots (https://github.com/nextcloud/screenshots/)
- [x] Verify that the new version number is shown in settings

- [x] Verify that it is shown on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (within 24h)
- [x] Inform marketing about changelog and expected release date

**Final Release, after two weeks time (max) of latest RC release**
- [x] Bump versionCode in ```app/build.gradle``` file
- [x] Verify that the new version number is shown in settings
- [x] Tag version as "v```13.0.0```" (as in ```^v[0-9]+\.[0-9]+\.[0-9]+$```)

- [x] Verify that it is shown on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (within 24h)
- [x] In case there were security issues fixed ping the security team

**After release**
- ```x.y``` - 1
  - [x] Delete ```stable-12.3``` branch
- ```x.y```
  - [x] Create milestone ```13.0.1```
  - [x] Schedule ```x.y.1 RC1``` 3 weeks after stable, release _~4 weeks_
  - [x] Create overview issue
- ```x.y``` + 1
  - [x] Create milestone ```13.1```
  - [x] Create overview issue & adjust date, handle bumps

Backports:
- [App backport requests](https://github.com/nextcloud/talk-android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

Open PRs:
- [Milestone](https://github.com/nextcloud/talk-android/pulls?q=is%3Aopen+is%3Apr+milestone%3A%22Nextcloud+App+13.0.0%22)

Marketing:
@jospoortvliet

**Comment by AndyScherzinger** [comment]
@timkrueger yeah, you are right, it is actually the next minor 👍 I'll fix the template! nice catch!

**Comment by AndyScherzinger** [comment]
While, when thinking about it, if @nickvergessen always wants to bind features to major releases on the server that major would actually be right and the next one would actually be 14.0.0 not 13.1.0, while also iOS is doing feature releases in between.

**Comment by nickvergessen** [comment]
Talk 14 should come on all platforms at the same time.
Whether in between the alpha builds are called 14.0.0 alpha 10000 or 13.99.0 or 13.x.y I don't really care.

**Comment by AndyScherzinger** [comment]
> Talk 14 should come on all platforms at the same time.

Of course

> Whether in between the alpha builds are called 14.0.0 alpha 10000 or 13.99.0 or 13.x.y I don't really care.

Sounds good to me, while it is not the alpha builds but the releases we do in-between, like only having a single feature release every 4 months is not very "mobile app"-y and I think it is also not was is being done on the iOS side. So 👍
