### ISSUE TITLE
common NC android lib: identify common code to NC android files

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#1775]
For the future it is planned to extract code that is used both in https://github.com/nextcloud/android and https://github.com/nextcloud/talk-android (and maybe more NC android apps).

For the common code there should be a new nextcloud android lib. 
Or maybe https://github.com/nextcloud/android-library is extended?
Also take into account https://github.com/stefan-niedermann/nextcloud-commons

This issue should be used to collect which code could be extracted to this common lib. Add ideas for common code to the list.
fyi @timkrueger @tobiasKaminsky @AlvaroBrey

**Ideas for code which could be extracted:**
- code for Firebase Cloud Messaging & pushproxy 
- Files upload
- logging & Exception reports, see https://github.com/nextcloud/talk-android/issues/1376 and https://github.com/stefan-niedermann/nextcloud-commons
- authentication
- user status https://github.com/nextcloud/talk-android/issues/898
- account switcher

**todos for a common lib**
- [x] new lib or existing lib?
- [x] which technologies/frameworks?

**Comment by tobiasKaminsky** [comment]
We should also check if not needed packages are stripped out, e.g. if we include nextcloud-commons with e.g. 200 classes, but we use only 2, then proguard/other shrinking systems should remove the others.

**Comment by tobiasKaminsky** [comment]
Plan
- [ ] Talk: integrate Log_OC to test
- [ ] Files: move LogsActivity to library
- [ ] Talk: make use of LogsActivity

**Comment by tobiasKaminsky** [comment]
Shrinking app:
- [ ] https://developer.android.com/studio/build/shrink-code#shrink-code
- [ ] how does this influence app?
- [ ] crash reports on play store still working?

**Comment by mahibi** [comment]
i will close this issue.

we now have:
- https://github.com/nextcloud/android-common 
   - for common features or utilities
   - Ideas for common code can be noted in https://github.com/nextcloud/android-common/issues/56

- https://github.com/nextcloud/android-config 
   - shared configs, synced to other repos by automated pull requests

- https://github.com/nextcloud/android-library 
   - library for accessing nextcloud from android apps
   - interface for any other android app to communicate with the nextcloud server, e.g. getting capabilities, getting status, getting files (so more kind of "low level" access to nextcloud)
   - Some content from this lib will be moved to android-common. Like logging utilities, user model...
