### ISSUE TITLE
Release 14.0.2 - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#1972]
**Planned RC1: 24th May 2022**

- [ ] Bump ```versionCode``` in ```app/build.gradle``` file
- [ ] Verify that the new version number is shown in settings

- [ ] Verify that it is shown on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (within 24h)
- [ ] Inform marketing about changelog and expected release date

**Final Release, after one weeks time (max) of latest RC release**
- [ ] Bump ```versionCode``` in ```app/build.gradle``` file
- [ ] Verify that the new version number is shown in settings

- [ ] Verify that it is shown on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (within 24h)
- [ ] In case there were security issues fixed ping the security team

Backports:
- [App backport requests](https://github.com/talk-android/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
