### ISSUE TITLE
Release 14.2.0 - Roadmap

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/talk-android#2214]
**Planned RC1: 16th August 2022**

**Release/EOL Management preparations (do this when creating new roadmap)**
- [x] [Create milestone](https://github.com/nextcloud/talk-android/milestones/new)
- [ ] Check if oldest Android version is EOL by Google and user usage <= 0.5% and drop it if so
  - [ ] Search for usage of Build.VERSION_CODES.xy
  - [ ] Announce it in [changelog](https://github.com/nextcloud/talk-android/blob/master/CHANGELOG.md)

**Create stable-x.y branch & use it for release (when releasing RC1)**
- [x] Create branch ```stable-14.2```
	- [ ] Enable branch to be analyzed on [codacy](https://app.codacy.com/gh/nextcloud/talk-android/settings/branches)
- [ ] Change on App
	- [ ] Check that transifex bot still works
- [ ] Update versionCode in ```app/build.gradle``` on ```master``` to next minor version

**Test app with all supported Android versions**
- Access all activities/controllers
- Chat: previews (media/contacts), text/voice-messages, reply/swipe-reply, delete, share file
- Call: audio/video
- Switch accounts
- Dark/light theme

All tests on
  - [ ] Android 5
  - [ ] Android 6
  - [ ] Android 7
  - [ ] Android 8
  - [ ] Android 9
  - [ ] Android 10
  - [ ] Android 11
  - [ ] Android 12

**RC1**
- [ ] Bump versionCode in ```app/build.gradle``` file
- [ ] Replace screenshots (https://github.com/nextcloud/screenshots/)
- [ ] Verify that the new version number is shown in settings

- [ ] ~~Verify that it is shown on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (within 24h)~~
- [ ] Inform marketing about changelog and expected release date

**Final Release, after two weeks time (max) of latest RC release**
- [x] Bump versionCode in ```app/build.gradle``` file
- [x] Verify that the new version number is shown in settings
- [x] Tag version as "v```14.2.0```" (as in ```^v[0-9]+\.[0-9]+\.[0-9]+$```)

- [ ] Verify that it is shown on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (within 24h)
- [ ] In case there were security issues fixed ping the security team

**After release**
- ```x.y``` - 1
  - [x] Delete ```stable-14.1``` branch
- ```x.y```
  - [x] Create milestone ```14.2.1```
  - [x] Schedule ```x.y.1 RC1``` 3 weeks after stable, release _~4 weeks_
  - [ ] Create overview issue
- ```x.y``` + 1
  - [x] Create milestone ```15.0```
  - [x] Create overview issue (#2158) & adjust date, handle bumps

Backports:
- [App backport requests](https://github.com/nextcloud/talk-android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

Open PRs:
- [Milestone](https://github.com/nextcloud/talk-android/pulls?q=is%3Aopen+is%3Apr+milestone%3A%2214.2.0%22)

**Comment by timkrueger** [comment]
In F-Droid since 04.09.2022
