### ISSUE TITLE
Release 14.2.1 - Roadmap

### ISSUE THREAD

**Issue by timkrueger** [nextcloud/talk-android#2342]
**Planned RC1: if needed**

- [ ] Bump ```versionCode``` in ```app/build.gradle``` file
- [ ] Verify that the new version number is shown in settings

- [ ] Verify that it is shown on [F-Droid](https://f-droid.org/de/packages/com.nextcloud.client/) (within 24h)

**Final Release, after one weeks time (max) of latest RC release**
- [ ] Bump ```versionCode``` in ```app/build.gradle``` file
- [ ] Verify that the new version number is shown in settings

- [ ] Verify that it is shown on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (within 24h)
- [ ] In case there were security issues fixed ping the security team

Backports:
- [App backport requests](https://github.com/talk-android/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)
