### ISSUE TITLE
Release 15.0.2 - Roadmap

### ISSUE THREAD

**Issue by timkrueger** [nextcloud/talk-android#2513]
**RC1: 22.11.2022**

- [x] Bump ```versionCode``` in ```app/build.gradle``` file
- [x] Verify that the new version number is shown in settings

- [x] Verify that it is shown on [F-Droid](https://f-droid.org/de/packages/com.nextcloud.client/) (within 24h)

**Final Release, after one weeks time (max) of latest RC release**
- [x] Bump ```versionCode``` in ```app/build.gradle``` file
- [x] Verify that the new version number is shown in settings

- [x] Verify that it is shown on [F-Droid](https://f-droid.org/en/packages/com.nextcloud.talk2/) (within 24h)
- [x] In case there were security issues fixed ping the security team

Backports:
- [App backport requests](https://github.com/talk-android/android/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abackport-request)

**Comment by ASerbinski** [comment]
Its been a few days and there is no hint of the RC on F-Droid. If it was, I'd be able to direct my users to it, but since the signatures are unique there, we are in a bit of a bind where its impossible to update.

**Comment by mahibi** [comment]
@ASerbinski unfortunately RC's are not released on F-Droid for now. 
https://github.com/nextcloud/talk-android/issues/2032

15.0.2 was just released and will arrive in gplay today / in F-Droid within ~24h

**Comment by ASerbinski** [comment]
@mahibi that's too bad the RC's aren't added there. Incidentally, it is for "files", and nicely separated by a setting (Expert mode --> Unstable updates). It would be nice if this could be added for talk at some point.

**Comment by mahibi** [comment]
> @mahibi that's too bad the RC's aren't added there. Incidentally, it is for "files", and nicely separated by a setting (Expert mode --> Unstable updates). It would be nice if this could be added for talk at some point.

thanks for the feedback @ASerbinski , i can raise this topic at the next meeting but i can't guarantee it for now
