### ISSUE TITLE
bump minSdkVersion to 26 (Android 8.0)

### ISSUE THREAD

**Issue by mahibi** [nextcloud/talk-android#4369]
came up because of 
https://github.com/nextcloud/talk-android/pull/4341#issuecomment-2431462607
https://github.com/nextcloud/talk-android/issues/4338

I just calculated the percentage usage of android 7.0 and 7.1 for our user base.

For 7.0 it is 0,3%
For 7.1 it is 0,19%

We have the rule to ditch android version lower than 0,5%.

# ToDo:

- [ ] remove checks for android versions older than api level 26
- [ ] bump minSdkVersion to 26
- [ ] update documentation at 
  - [ ] https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#mobile-apps
  - [ ] https://nextcloud-talk.readthedocs.io/en/latest/user-requirements/#mobile-apps
