### ISSUE TITLE
New account switcher

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/talk-android#909]
As discussed with @jancborchardt the account switcher should be the same like on Nextcloud Files:

![2020-10-06-141931](https://user-images.githubusercontent.com/5836855/95200608-f9cc9300-07de-11eb-8c67-7d9a7e5d1fe5.png)

Beneath account switcher we show "Settings" which then shows the current settings.
In Settings:
- remove click on account action

TODOs
* [x] add account switcher dialog #1239
* [x] remove account actions from settings  #1239
* [x] (tbd via #1278) add "manage accounts" and remove remaining accounts actions from settings screen, except the ones mentioned in #1058 (move them to advanced (or rather also the the manage accounts item actions)

**Comment by nickvergessen** [comment]
So close this issue or #1058 @AndyScherzinger ?

**Comment by AndyScherzinger** [comment]
@nickvergessen both issues are still relevant :/ We don't have the manage accounts part yet and we didn't fully simplify the settings yet with respect to the account part. To make things easier we could merge them and close at least one of them.

**Comment by AndyScherzinger** [comment]
@nickvergessen did yome housekeeping to only have the parts open via issues that are left to be implemented
